# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReQuest_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReQuest_ios
  pod 'ARCL', :path => '/Users/leonmak/Desktop/ARKit-practice/ARKit-CoreLocation'
  pod "TimelineTableViewCell"
  pod 'TJProfileImage'
  pod 'TextFieldEffects'	
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
